# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-04-22 05:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='电影名称')),
                ('score', models.CharField(max_length=10, verbose_name='电影评分')),
                ('desc', models.CharField(max_length=30, verbose_name='一句话影评')),
                ('image', models.CharField(max_length=50, verbose_name='图片地址')),
                ('detail_link', models.CharField(max_length=50, verbose_name='详情页链接')),
            ],
            options={
                'db_table': 'tb_movie',
                'verbose_name': '电影信息',
            },
        ),
        migrations.CreateModel(
            name='MovieDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direct', models.CharField(max_length=30, verbose_name='电影名称')),
                ('etc', models.CharField(max_length=30, verbose_name='电影名称')),
                ('performer', models.CharField(max_length=30, verbose_name='电影名称')),
                ('types', models.CharField(max_length=30, verbose_name='电影名称')),
                ('address', models.CharField(max_length=30, verbose_name='电影名称')),
                ('language', models.CharField(max_length=30, verbose_name='电影名称')),
                ('date', models.CharField(max_length=30, verbose_name='电影名称')),
                ('for_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Movie', verbose_name='movie')),
            ],
        ),
    ]
