# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-04-24 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image_file_id',
            field=models.CharField(max_length=80, null=True, verbose_name='图片file_id'),
        ),
    ]
