# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-04-22 05:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moviedetail',
            options={'verbose_name': '电影详情信息'},
        ),
        migrations.AlterModelTable(
            name='moviedetail',
            table='tb_detail',
        ),
    ]
