# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-04-24 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_movie_image_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='detail_link',
            field=models.ImageField(null=True, upload_to='', verbose_name='详情页链接'),
        ),
    ]
