# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-04-22 05:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20200422_0533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviedetail',
            name='for_key',
        ),
    ]
