# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-04-22 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_remove_moviedetail_for_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedetail',
            name='date',
            field=models.CharField(max_length=100, verbose_name='上映日期'),
        ),
    ]
