# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-04-22 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20200422_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedetail',
            name='date',
            field=models.CharField(max_length=256, verbose_name='上映日期'),
        ),
        migrations.AlterField(
            model_name='moviedetail',
            name='performer',
            field=models.CharField(max_length=256, verbose_name='主演'),
        ),
    ]
